### ISSUE TITLE
404: Blob does not exist

### ISSUE THREAD

**Issue by rgknp** [Azure/ACS-Deployment-Tutorial#1]
@ilkarman, @msalvaris
I tried running 00_BuildImage.ipynb but it fails at step 3
!wget "https://migonzastorage.blob.core.windows.net/deep-learning/models/cntk/imagenet/ResNet_152.model"

--2017-05-31 19:47:39--  https://migonzastorage.blob.core.windows.net/deep-learning/models/cntk/imagenet/ResNet_152.model
Resolving migonzastorage.blob.core.windows.net (migonzastorage.blob.core.windows.net)... 191.235.192.206
Connecting to migonzastorage.blob.core.windows.net (migonzastorage.blob.core.windows.net)|191.235.192.206|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2017-05-31 19:47:39 ERROR 404: The specified blob does not exist..

**Comment by msalvaris** [comment]
Reuploaded, try again
