### ISSUE TITLE
az command not working on VM

### ISSUE THREAD

**Issue by rgknp** [Azure/ACS-Deployment-Tutorial#2]
@ilkarman, @msalvaris
I am using 02_DeployOnACS notebook on Azure Linux Data Science VM.
DSVM comes preinstalled with Azure CLI. Location is /anaconda/envs/py35/bin/az

When I run 
!az login -o table 
I get error 
/bin/sh: az: command not found

When I run 
!/anaconda/envs/py35/bin/az login -o table
I get error
/usr/bin/python: No module named azure

It appears to me that Python kernel running in Jupyter is referring to a different Python location while az command needs Python installed in some other locatiom.

**Comment by msalvaris** [comment]
You need to run your Jupyter notebook from the environment that has the azure-cli installed. The kernel of the notebook does not apply to terminal commands. Hope that helps

**Comment by rgknp** [comment]
@msalvaris, I still have this issue. I thought issue is because I am using Linux DSVM. Now I installed Jupyter locally and running 02_DeployonACS. It gets stuck at first az command. I can see Kernel is busy but there is no pop up asking for Azure device login. It just hangs there.
I tried both with IE and Chrome its the same issue. I ensured pop up is not blocked in both browsers.

az command works when I try it locally within a python script. For example this works
import os
os.system('az login -o table')

**Comment by msalvaris** [comment]
@rgknp It should work fine on the Linux DSVM
Can you try a couple of things for me
Can you run the following in the environment and in the Jupyter notebook?
which az

They should be the same. If not make sure you are running your Jupyter notebook from the same environment as you have az installed. So:
source activate py35; jupyter notebook
